<template>
  <div class="app">
    <h1>{{ msg }}</h1>
    <p>Generated by cqin-cli</p>
  </div>
</template>

<script>
<% if (language === 'TypeScript') { %>
export default {
  name: 'App',
  data() { msg: string } {
    return {
      msg: '<%= msg %>'
    }
  }
}
<% } else { %>
export default {
  data() {
    return {
      msg: '<%= msg %>'
    }
  }
}
<% } %>
</script>

<style scoped>
.app {
  color: #42b983;
}
</style>